version: "3"
services:

  db:
    image: postgres:10.4

  sqs:
    image: pakohan/elasticmq
    hostname: sqs

  django:
    env_file:
      - docker/prod/docker_production.env
    build:
      context: ./
      dockerfile: docker/prod/django/Dockerfile
    depends_on:
      - db
      - sqs
    ports:
      - "127.0.0.1:8000:8000"

  worker:
    build:
      context: ./
      dockerfile: docker/prod/worker/Dockerfile
    depends_on:
      - django
    env_file:
      - docker/prod/docker_production.env

  nodejs:
    build:
      context: ./
      dockerfile: docker/prod/nodejs/Dockerfile
      args:
        NODE_ENV: production
    depends_on:
      - django
    ports:
      - "127.0.0.1:8888:80"
    volumes:
      - /code/node_modules
      - /code/bower_components

  # remote-worker:
  #   build:
  #     context: ./
  #     dockerfile: docker/prod/worker/Dockerfile
  #   command: ["python", "-m", "scripts.workers.remote_submission_worker"]
  #   env_file:
  #     - docker/prod/docker_remote_worker.env
