version: "3"
services:

  db:
    image: postgres:10.4

  sqs:
    image: pakohan/elasticmq
    hostname: sqs

  django:
    hostname: django
    env_file:
      - docker/dev/docker.env
    build:
      context: ./
      dockerfile: docker/dev/django/Dockerfile
    depends_on:
      - db
      - sqs
    volumes:
      - .:/code

  worker:
    env_file:
      - docker/dev/docker.env
    build:
      context: ./
      dockerfile: docker/dev/worker/Dockerfile
    depends_on:
      - django
    volumes:
      - .:/code

  nodejs:
    hostname: nodejs
    build:
      context: ./
      dockerfile: docker/dev/nodejs/Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - .:/code
      - /code/node_modules
      - /code/bower_components
